--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "UTEC"."LOCALIDADES" 
   (	"IDLOCALIDAD" NUMBER(19,0), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"IDDEPARTAMENTO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072751
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072751" ON "UTEC"."LOCALIDADES" ("IDLOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_FV9L7R4W12J56RQXL0MDR4L4O
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."UK_FV9L7R4W12J56RQXL0MDR4L4O" ON "UTEC"."LOCALIDADES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "UTEC"."LOCALIDADES" ADD CONSTRAINT "UK_FV9L7R4W12J56RQXL0MDR4L4O" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UTEC"."LOCALIDADES" MODIFY ("IDLOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."LOCALIDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."LOCALIDADES" MODIFY ("IDDEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."LOCALIDADES" ADD PRIMARY KEY ("IDLOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "UTEC"."LOCALIDADES" ADD CONSTRAINT "FKSCKAP9AHU3VKCOLKAM66CDFU7" FOREIGN KEY ("IDDEPARTAMENTO")
	  REFERENCES "UTEC"."DEPARTAMENTOS" ("IDDEPARTAMENTO") ENABLE;
