--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AREAS
--------------------------------------------------------

  CREATE TABLE "UTEC"."AREAS" 
   (	"IDAREA" NUMBER(19,0), 
	"DESCRIPCION" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072687
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072687" ON "UTEC"."AREAS" ("IDAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_GFJPUPCSJ6Q9KRFLY8BFKP47E
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."UK_GFJPUPCSJ6Q9KRFLY8BFKP47E" ON "UTEC"."AREAS" ("DESCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AREAS
--------------------------------------------------------

  ALTER TABLE "UTEC"."AREAS" ADD CONSTRAINT "UK_GFJPUPCSJ6Q9KRFLY8BFKP47E" UNIQUE ("DESCRIPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UTEC"."AREAS" MODIFY ("IDAREA" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."AREAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."AREAS" ADD PRIMARY KEY ("IDAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
