--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANALISTAS
--------------------------------------------------------

  CREATE TABLE "UTEC"."ANALISTAS" 
   (	"FIRMADIGITAL" VARCHAR2(255 CHAR), 
	"IDUSUARIO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072684
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072684" ON "UTEC"."ANALISTAS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ANALISTAS
--------------------------------------------------------

  ALTER TABLE "UTEC"."ANALISTAS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."ANALISTAS" ADD PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALISTAS
--------------------------------------------------------

  ALTER TABLE "UTEC"."ANALISTAS" ADD CONSTRAINT "FKC2F2YVSAQ0AYCNN4Q3U4SYRWP" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "UTEC"."USUARIOS" ("IDUSUARIO") ENABLE;
