--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TUTORES
--------------------------------------------------------

  CREATE TABLE "UTEC"."TUTORES" 
   (	"IDUSUARIO" NUMBER(19,0), 
	"IDAREA" NUMBER(19,0), 
	"IDROL" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072797
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072797" ON "UTEC"."TUTORES" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TUTORES
--------------------------------------------------------

  ALTER TABLE "UTEC"."TUTORES" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."TUTORES" MODIFY ("IDAREA" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."TUTORES" MODIFY ("IDROL" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."TUTORES" ADD PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TUTORES
--------------------------------------------------------

  ALTER TABLE "UTEC"."TUTORES" ADD CONSTRAINT "FKLLH7A6W90KP7OJQAMFTPBOW0A" FOREIGN KEY ("IDAREA")
	  REFERENCES "UTEC"."AREAS" ("IDAREA") ENABLE;
  ALTER TABLE "UTEC"."TUTORES" ADD CONSTRAINT "FKDWCR71WGPFBGKKP275EIRXIDM" FOREIGN KEY ("IDROL")
	  REFERENCES "UTEC"."ROLES" ("IDROL") ENABLE;
  ALTER TABLE "UTEC"."TUTORES" ADD CONSTRAINT "FK79GABDIEJNC6N8F7UBGSEYTLW" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "UTEC"."USUARIOS" ("IDUSUARIO") ENABLE;
