--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITRS
--------------------------------------------------------

  CREATE TABLE "UTEC"."ITRS" 
   (	"IDITR" NUMBER(19,0), 
	"ACTIVO" CHAR(1 CHAR), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"IDDEPARTAMENTO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072742
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072742" ON "UTEC"."ITRS" ("IDITR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_THMCQ1LQCU6PW4KA0PAIB47Y9
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."UK_THMCQ1LQCU6PW4KA0PAIB47Y9" ON "UTEC"."ITRS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ITRS
--------------------------------------------------------

  ALTER TABLE "UTEC"."ITRS" ADD CONSTRAINT "UK_THMCQ1LQCU6PW4KA0PAIB47Y9" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UTEC"."ITRS" MODIFY ("IDITR" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."ITRS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."ITRS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."ITRS" MODIFY ("IDDEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."ITRS" ADD PRIMARY KEY ("IDITR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITRS
--------------------------------------------------------

  ALTER TABLE "UTEC"."ITRS" ADD CONSTRAINT "FKRWHSJ9M3TUSVU6UEIHHOJAWYV" FOREIGN KEY ("IDDEPARTAMENTO")
	  REFERENCES "UTEC"."DEPARTAMENTOS" ("IDDEPARTAMENTO") ENABLE;
