--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "UTEC"."USUARIOS" 
   (	"IDUSUARIO" NUMBER(19,0), 
	"ACTIVO" CHAR(1 CHAR), 
	"CLAVE" VARCHAR2(255 CHAR), 
	"CONFIRMADO" CHAR(1 CHAR), 
	"DOCUMENTO" NUMBER(10,0), 
	"FECHA_NACIMIENTO" TIMESTAMP (6), 
	"MAIL_INSTITUCIONAL" VARCHAR2(255 CHAR), 
	"MAIL_PERSONAL" VARCHAR2(255 CHAR), 
	"PRIMER_APELLIDO" VARCHAR2(255 CHAR), 
	"PRIMER_NOMBRE" VARCHAR2(255 CHAR), 
	"SEGUNDO_APELLIDO" VARCHAR2(255 CHAR), 
	"SEGUNDO_NOMBRE" VARCHAR2(255 CHAR), 
	"TELEFONO" VARCHAR2(255 CHAR), 
	"TIPO_USUARIO" VARCHAR2(255 CHAR), 
	"USUARIO" VARCHAR2(255 CHAR), 
	"IDDEPARTAMENTO" NUMBER(19,0), 
	"IDGENERO" NUMBER(19,0), 
	"IDITR" NUMBER(19,0), 
	"IDLOCALIDAD" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0072805
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."SYS_C0072805" ON "UTEC"."USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_SALCL0N4M3KUBQPLL79BF5PRI
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."UK_SALCL0N4M3KUBQPLL79BF5PRI" ON "UTEC"."USUARIOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_G1JVOF809ND5GY9Y03319UR7R
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTEC"."UK_G1JVOF809ND5GY9Y03319UR7R" ON "UTEC"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("CONFIRMADO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("PRIMER_APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("PRIMER_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "UTEC"."USUARIOS" ADD PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "UK_SALCL0N4M3KUBQPLL79BF5PRI" UNIQUE ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "UK_G1JVOF809ND5GY9Y03319UR7R" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "FKO6LD94TTD2HOOJDRXDAMIIY0O" FOREIGN KEY ("IDDEPARTAMENTO")
	  REFERENCES "UTEC"."DEPARTAMENTOS" ("IDDEPARTAMENTO") ENABLE;
  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "FKOD80LBXXEU1SFT09IUS6HU9WY" FOREIGN KEY ("IDGENERO")
	  REFERENCES "UTEC"."GENEROS" ("IDGENERO") ENABLE;
  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "FK30Y7SGT4G22VUKIUEQFDNH0RG" FOREIGN KEY ("IDITR")
	  REFERENCES "UTEC"."ITRS" ("IDITR") ENABLE;
  ALTER TABLE "UTEC"."USUARIOS" ADD CONSTRAINT "FKD25T9FRM9KMWXAC14K3K6HYII" FOREIGN KEY ("IDLOCALIDAD")
	  REFERENCES "UTEC"."LOCALIDADES" ("IDLOCALIDAD") ENABLE;
